import type { Metadata } from "next";
import "../globals.css";
import PublicHeader from "@/components/layouts/publicHeader"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function PublicLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <PublicHeader></PublicHeader>
            {children}
        </>
    );
}
